name: PaxD
author: mralfiem591
version: 26.0.25
description: The main command line tool for using PaxD.
license: MIT
tags:
- cli
- package manager
- installer
- windows
- tool
- gateway
- http
- repository
install:
  files:
  - paxd.py
  - run_pkg.py
  - repository
  - LICENSE
  dependencies:
    pip:
    - requests
    - colorama
    - argparse
    - pyyaml
    - sentry-sdk
    - uv
    paxd:
    - com.mralfiem591.paxd-sdk
    - com.mralfiem591.paxd-imageview
  firstrun: true
  updaterun: true
  exclude_from_updates:
  - repository
  main_executable: paxd.py
  command_alias: paxd
  supports_fastxd: false
  checksum:
    run_pkg.py: sha256:08ae0d8c39c2992beddc59ea232288db9a1b2bf57bc3738e91157955a1d5ff6e
    repository: sha256:fce8a9a6b04bb38968943c20e1d6c594304b7d43f877aa014dccea3365f47055
    LICENSE: sha256:f5382f6ba1a0e00d6eeed6e1ce4430b552a3e694b61a529526c29ccaeacea11f
    paxd.py: sha256:a8249d452803c6ee21e9dff3de1e15e98ce3c992e7e7e7b366f1e9507f902637
    asset/logo.png: sha256:439524e5fbead18454271c1fb316465c5bb3189cf19a0596db757f5396988e61
