name: PaxD
author: mralfiem591
version: 26.1.0
description: The main command line tool for using PaxD.
license: MIT
tags:
- cli
- package manager
- installer
- windows
- tool
- gateway
- http
- repository
install:
  files:
  - paxd.py
  - run_pkg.py
  - repository
  - LICENSE
  dependencies:
    pip:
    - requests
    - colorama
    - argparse
    - pyyaml
    - sentry-sdk
    - uv
    paxd:
    - com.mralfiem591.paxd-sdk
    - com.mralfiem591.paxd-imageview
  firstrun: true
  updaterun: true
  exclude_from_updates:
  - repository
  main_executable: paxd.py
  command_alias: paxd
  supports_fastxd: false
  checksum:
    run_pkg.py: sha256:08ae0d8c39c2992beddc59ea232288db9a1b2bf57bc3738e91157955a1d5ff6e
    repository: sha256:20c8fd85af1f2f2ac54cc2a609e9021ccce29d59ee2b7c5b7460fbe10fd24613
    LICENSE: sha256:f5382f6ba1a0e00d6eeed6e1ce4430b552a3e694b61a529526c29ccaeacea11f
    paxd.py: sha256:1ddd2a6529812e5253e80b2c730f20f3e99b878ca0a0e60742fe56f840d1b542
    asset/logo.png: sha256:439524e5fbead18454271c1fb316465c5bb3189cf19a0596db757f5396988e61
