name: PaxD
author: mralfiem591
version: 26.0.28
description: The main command line tool for using PaxD.
license: MIT
tags:
- cli
- package manager
- installer
- windows
- tool
- gateway
- http
- repository
install:
  files:
  - paxd.py
  - run_pkg.py
  - repository
  - LICENSE
  dependencies:
    pip:
    - requests
    - colorama
    - argparse
    - pyyaml
    - sentry-sdk
    - uv
    paxd:
    - com.mralfiem591.paxd-sdk
    - com.mralfiem591.paxd-imageview
  firstrun: true
  updaterun: true
  exclude_from_updates:
  - repository
  main_executable: paxd.py
  command_alias: paxd
  supports_fastxd: false
  checksum:
    LICENSE: sha256:c856d6c33a97f74f274e7d7bee176b0515f34631d34642ec95a0156df614e207
    paxd.py: sha256:55000d2abd6ea0b6f973a8797684c755ee62777c0c4066f2bbacae8e1a308170
    repository: sha256:fce8a9a6b04bb38968943c20e1d6c594304b7d43f877aa014dccea3365f47055
    run_pkg.py: sha256:130bfe4cb94abfe496824d2a49bc5c53d213b7c02181bf61d46d926fccb461d7
    asset/logo.png: sha256:439524e5fbead18454271c1fb316465c5bb3189cf19a0596db757f5396988e61
