name: PaxD Imageview
author: mralfiem591
version: 1.1.4
description: A simple image viewer used by PaxD.
license: MIT
tags:
- cli
- image viewer
- image renderer
- windows
- tool
install:
  files:
  - imageview.py
  - LICENSE
  dependencies:
    pip:
    - requests
    - Pillow
    - ascii_magic
  firstrun: false
  updaterun: false
  main_executable: imageview.py
  command_alias: paxd-imageview
  supports_fastxd: true
  checksum:
    imageview.py: sha256:11e974422891570093f4438c404bfc3c13e03aaa788418a8c93a0d8b0bcc0dbb
    LICENSE: sha256:c856d6c33a97f74f274e7d7bee176b0515f34631d34642ec95a0156df614e207
