name: PaxD SDK
author: mralfiem591
version: 1.2.6
description: The main SDK (Software Development Kit) for PaxD.
license: MIT
tags:
- sdk
- development
- devkit
install:
  files:
  - main.py
  firstrun: false
  updaterun: false
  exclude_from_updates: []
  supports_fastxd: false
  checksum:
    main.py: sha256:27caf49e778c5330ad16678b47d5ca60a0391e136a30cab5f87970566213686d
