name: PaxD GUI
author: mralfiem591
version: 1.1.13
description: A graphical user interface for PaxD package management.
license: MIT
tags:
- gui
- package manager
- installer
- windows
- paxd
- graphical
- tkinter
install:
  files:
  - paxd_gui.py
  dependencies:
    pip:
    - requests
    paxd:
    - com.mralfiem591.paxd-sdk
    - com.mralfiem591.paxd
  firstrun: true
  updaterun: false
  main_executable: paxd_gui.py
  command_alias: paxd-gui
  supports_fastxd: false
  checksum:
    paxd_gui.py: sha256:c81db056243ab48fb17c3ea3e207ec4993c06b3ba99af372b193986c845169d0
