name: PaxD Vulnerability Scanner
author: mralfiem591
version: 1.0.4
description: A simple vulnerability scanner for PaxD.
license: MIT
tags:
- cli
- vulnerability
- windows
- tool
install:
  files:
  - main.py
  dependencies:
    pip:
    - requests
    - colorama
    paxd:
    - com.mralfiem591.paxd-sdk
  firstrun: false
  updaterun: false
  main_executable: main.py
  command_alias: paxd-vulnscan
  supports_fastxd: false
  checksum:
    main.py: sha256:fa0c134cc5178860347cb35b2465ef4358b67b0b38c1f6f2b6eea11799e9be57
