name: PaxD Vulnerability Scanner
author: mralfiem591
version: 1.0.3
description: A simple vulnerability scanner for PaxD.
license: MIT
tags:
- cli
- vulnerability
- windows
- tool
install:
  files:
  - main.py
  dependencies:
    pip:
    - requests
    - colorama
    paxd:
    - com.mralfiem591.paxd-sdk
  firstrun: false
  updaterun: false
  main_executable: main.py
  command_alias: paxd-vulnscan
  supports_fastxd: false
  checksum:
    main.py: sha256:e30cd38430815e7067522ced52b61ad986a64f11781b8d86c1ed2613ca7cbc7c
