name: PaxD Improved
author: mralfiem591
version: 1.0.2
description: A modern, beautiful command line interface for PaxD using Rich for enhanced
  user experience.
license: MIT
tags:
- cli
- package manager
- installer
- windows
- tool
- rich
- modern ui
- improved ux
install:
  files:
  - paxd_improved.py
  - repository
  dependencies:
    pip:
    - requests
    - rich
    - pyyaml
    - argparse
    paxd:
    - com.mralfiem591.paxd-sdk
    - com.mralfiem591.paxd
  firstrun: true
  updaterun: false
  exclude_from_updates:
  - repository
  main_executable: paxd_improved.py
  command_alias: paxd
  supports_fastxd: false
  checksum:
    repository: sha256:fce8a9a6b04bb38968943c20e1d6c594304b7d43f877aa014dccea3365f47055
    paxd_improved.py: sha256:56007036eed3bd5f422bb9cc913a92da5d4a8c0bd7eb42a7a215af2549e1c389
